language: elixir
elixir:
  - 1.2.6
otp_release:
  - 18.1
addons:
  s3_region: "us-east-1"
  artifacts:
    key: "AKIAJCDN2QCGD5GTOQAA"
    bucket: "my-app-builds"
    region: "us-east-1"
    paths:
      - ./my_app_prod.tar.gz
    target_paths: "$TRAVIS_COMMIT"
script:
  - mix test --exclude noci
after_success:
  - MIX_ENV=prod mix do compile, release
  - cp rel/my_app/releases/*/my_app.tar.gz my_app_prod.tar.gz
